base_dir: ./ # Base directory where code is being run
output_dir: ./output # Where to save output to
log_level: info # Verbosity used in logging
cores: 2 # Number of cores to use when processing
width: 3 # Width of structure
height: 6 # Height of structure
stress_tensile: 1.0 # Tensile stress
stress_compressive: 1.0 # Compressive stress
joint_cost: 0.0 # Joint costs
loaded_points: # Loaded points
  - [3, 3]
load_direction: # Load direction
  - 0.0
  - -1.0
load_large: 50.0 # Large load
load_small: 5.0 # Small load
max_length: 18.0 # Max length
support_points: # Support points
  - []
filter_levels: [] # List of values to filter by if empty no filtering is performed
primal_method: load_factor # Primal method
problem_name: short cantilever # Problem name
csv_filename: results.csv # Filename to save results to, if left as `results.csv` will have YYYY-MM-DD-hhmmss added
notes: short cantilever test # Notes to include
